# TODO: security best practices (container + full)
# TODO: liveness and readiness probes
# TODO: ephemeral temp volume (ask about storage requirements)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eos{{ .Values.modelName }}
  namespace: models
spec:
  # TODO: use helm lookup function to find existing deployments replicas
  replicas: 0
  selector:
    matchLabels:
      app: eos
      model: {{ squote .Values.modelName }}
  template:
    metadata:
      labels:
        app: eos
        model: {{ squote .Values.modelName }}
    spec:
      containers:
        - name: model
          image: ersiliaos/eos{{ .Values.modelName }}:latest
          ports:
            - containerPort: 80
              protocol: TCP
          resources: 
            requests:
              cpu: 10m
              memory: {{ .Values.memoryRequirement }}
            limits:
              cpu: 1000m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
                # TODO: add memory label to node
              {{ if eq .Values.memoryRequirement "1Gi" -}}
              - key: name
                operator: In
                values:
                - worker-node-1
              {{- else if eq .Values.memoryRequirement "6Gi" -}}
              - key: name
                operator: In
                values:
                - model-nodes-8g
              {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
