apiVersion: 1.0.0
name: ingress-nginx
description: A Helm chart for implementing an ingress-nginx
version: 1.0.0

dependencies:
  - name: ingress-nginx
    version: 4.12.0
    repository: https://kubernetes.github.io/ingress-nginx