ingress:
  albName: ersilia-nginx-ingress
  ingressClassName: alb

nginx:
  namespaceOverride: ingress-nginx

  serverBlock: |-
    server {
      listen 8080;
      
      location /models/3804 {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://eos-model-3804.eos-models.svc.cluster.local:80;
      }
    }
