{{- if and .Values.alpineBox .Values.alpineBox.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-alpine
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alpine
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate: {}
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: alpine
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: alpine
    spec:
      containers:
        - name: alpine
          image: docker.io/alpine:latest
          imagePullPolicy: "IfNotPresent"
          command:
            - /bin/sh
          args:
            - -ec
            - |
              #!/bin/sh
              while true; do
                sleep 100000
              done
          securityContext:
            allowPrivilegeEscalation: false
            # capabilities:
            #   drop:
            #   - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 300m
              ephemeral-storage: 1Gi
              memory: 512Mi
            requests:
              cpu: 10m
              ephemeral-storage: 50Mi
              memory: 50Mi
          volumeMounts:
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
      volumes:
        - name: empty-dir
          emptyDir: {}
{{- end }}