apiVersion: apps/v1
kind: Deployment
metadata:
  name: ersiliaos-eos80ch
  namespace: model-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eos-demo
  template:
    metadata:
      labels:
        app: eos-demo
    spec:
      containers:
        - name: eos80ch
          image: ersiliaos/eos80ch:latest
          ports:
            - containerPort: 80